stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  REPOSITORY: eu.gcr.io/second-caster-232215

.build:
  stage: build
  image: docker
  services:
    - docker:19.03.0-dind
  script:
    - echo $GCE_SA_DEV | docker login -u _json_key --password-stdin https://eu.gcr.io
    - echo "Buiding service $SERVICE"
    - docker build . -t $REPOSITORY/$SERVICE:$IMAGE_TAG --build-arg SERVICE=$SERVICE
    - docker push $REPOSITORY/$SERVICE:$IMAGE_TAG

### JOB
do-al-collector-service build:
  extends: .build
  variables:
    SERVICE: do-al-collector-service
  only:
    changes:
      - "do-al-collector-service/*"
    variables:
      - $BUILD_AL_COLLECTOR == "true"