# do-ap-collector-service
do-ap-collector-service build:
  extends: .build
  variables:
    SERVICE: do-ap-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-ap-collector-service/*"

DEV do-ap-collector-service deploy:
  extends: .deploy
  needs:
    - do-ap-collector-service build
  tags:
    - jusintelligence
  variables:
    NAMESPACE: dev
    SERVICE: do-ap-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-ap-collector-service/*"

STAGING do-ap-collector-service deploy:
  extends: .deploy
  needs:
    - do-ap-collector-service build
  tags:
    - jusintelligence
  variables:
    NAMESPACE: staging
    SERVICE: do-ap-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-ap-collector-service/*"
      when: manual

PROD do-ap-collector-service deploy:
  extends: .deploy
  needs:
    - do-ap-collector-service build
  tags:
    - jusintelligence
  variables:
    NAMESPACE: prod
    SERVICE: do-ap-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-ap-collector-service/*"
      when: manual
