# do-trf4-collector-service
do-trf4-collector-service build:
  extends: .build
  variables:
    SERVICE: do-trf4-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-trf4-collector-service/*"

DEV do-trf4-collector-service deploy:
  extends: .deploy
  needs:
    - do-trf4-collector-service build
  tags:
    - jusintelligence
  variables:
    NAMESPACE: dev
    AMBIENTE: dev
    SERVICE: do-trf4-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-trf4-collector-service/*"

STAGING do-trf4-collector-service deploy:
  extends: .deploy
  needs:
    - do-trf4-collector-service build
  tags:
    - jusintelligence
  variables:
    NAMESPACE: staging
    AMBIENTE: staging
    SERVICE: do-trf4-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-trf4-collector-service/*"
      when: manual

PROD do-trf4-collector-service deploy:
  extends: .deploy
  needs:
    - do-trf4-collector-service build
  tags:
    - jusintelligence
  variables:
    NAMESPACE: prod
    AMBIENTE: prod
    SERVICE: do-trf4-collector-service
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      changes:
        - "do-trf4-collector-service/*"
      when: manual
